# Google Cloud Build configuration
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/note-taking-api:latest'
      - '-f'
      - 'Dockerfile.production'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/note-taking-api:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'note-taking-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/note-taking-api:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'cloud-run-sa@$PROJECT_ID.iam.gserviceaccount.com'
      - '--vpc-connector'
      - 'note-taking-connector'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,DB_HOST=34.135.245.229,DB_NAME=note_taking_db,DB_USER=noteuser,REDIS_URL=redis://10.227.108.131:6379/0'
      - '--set-secrets'
      - 'DB_PASSWORD=db-password:latest,SECRET_KEY=jwt-secret:latest,API_KEY=api-key:latest'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-central1:note-taking-db'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

# Substitutions (can be overridden at trigger time)
substitutions:
  _REGION: us-central1

# Build timeout
timeout: '1200s'

# Use kaniko for faster builds (optional)
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY 